services:
  # AI 서버
  ai-server:
    build: ./ai-server
    ports:
      - "8000:8000"
    volumes:
      - ./ai-server:/app # Hot Reload
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434 # Local Ollama

  # Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # DB
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: study_db