server:
  port: 8080

spring:
  application:
    name: demo

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/demo
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 1000
        format_sql: true

  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

logging:
  level:
    org.springframework: DEBUG

jwt:
  secret:
    key: ${JWT_SECRET_KEY:studyflowaitypesecrettestkey32charsplus}
  token:
    expiration: 3600000
    refresh-expiration: 604800000

groq:
  api:
    key: ${GROQ_API_KEY:}
    url: https://api.groq.com/openai/v1/chat/completions

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY:dummy}
      secret-key: ${AWS_SECRET_KEY:dummy}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    s3:
      bucket: ${AWS_BUCKET_NAME:dummy}

sentry:
  dsn: https://b187f1c104652f40887814505a05bc80@o4511190659301376.ingest.us.sentry.io/4511190708453376
  send-default-pii: true
  traces-sample-rate: 1.0

