name: Deploy to AWS Lightsail

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: MAIL_USERNAME,MAIL_PASSWORD,JWT_SECRET_KEY,AWS_ACCESS_KEY,AWS_SECRET_KEY,AWS_REGION,GROQ_API_KEY,AWS_BUCKET_NAME,ANTHROPIC_API_KEY
          script: |
            cd ~/Study-Flow_AI
            git pull origin main
            
            echo "MAIL_USERNAME=$MAIL_USERNAME" > .env
            echo "MAIL_PASSWORD=$MAIL_PASSWORD" >> .env
            echo "JWT_SECRET_KEY=$JWT_SECRET_KEY" >> .env
            echo "AWS_ACCESS_KEY=$AWS_ACCESS_KEY" >> .env
            echo "AWS_SECRET_KEY=$AWS_SECRET_KEY" >> .env
            echo "AWS_REGION=$AWS_REGION" >> .env
            echo "GROQ_API_KEY=$GROQ_API_KEY" >> .env
            echo "AWS_BUCKET_NAME=$AWS_BUCKET_NAME" >> .env
            echo "ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY" >> .env
            
            docker-compose down
            docker-compose up -d --build
